services:
  backend:
    image: ${REGISTRY_URL}/ktb-spring:latest
    container_name: ktb-spring
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    volumes:
      - /home/ubuntu/be/uploads:/app/uploads